# Generated by Django 6.0.1 on 2026-01-23 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['DepartmentNumber'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductNumber', models.CharField(max_length=50, unique=True)),
                ('ProductDate', models.DateField()),
                ('DepartmentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.department')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['ProductName'],
            },
        ),
    ]
